### ISSUE TITLE
关于登录版本过低的问题

### ISSUE THREAD

**Issue by MuXia-0326** [yunzai-org/yunzaijs#5]
试用了一下v4 发现登录的时候登录版本过低，现在签名api还在更新吗？之前用的一个docker版本的，没有后续没有更新了，导致现在登录失败

项目后期有更换登录方式的打算吗？

**Comment by ningmengchongshui** [comment]
关于登录方式。在未来会主动进行多协议，或交给trss进行扩展。签名问题是敏感性问题，请自行查阅相关协议资源，此处不做解答。

**Comment by MuXia-0326** [comment]
好的
