### ISSUE TITLE
不推荐使用dirent.parentPath或dirent.path

### ISSUE THREAD

**Issue by V2233** [yunzai-org/yunzaijs#8]
在node官方文档中属于实验性API且其中一个已废弃，自测在多个node版本找不到该属性，推荐改为以下路径：
![e2401bd6a2a940834218c8dd37bd748e](https://github.com/user-attachments/assets/6
![b409b25198e1734a8244d2cf521b2411](https://github.com/user-attachments/assets/819e4847-ce1b-4df1-b082-4a0cda83382d)
329223d-e613-4949-b2f3-00cf58bd7dd2)

**Comment by V2233** [comment]
![e2401bd6a2a940834218c8dd37bd748e](https://github.com/user-attachments/assets/f949720b-e41a-456b-8d96-1acbc40e4d71)

**Comment by ningmengchongshui** [comment]
V4.1.18已做兼容
